export * from "./auth.schema";
export * from "./vehicle.schema";
export * from "./driver.schema";
export * from "./documentType.schema";
export * from "./document.schema";
export * from "./fastag.schema";
export * from "./insurance.schema";
export * from "./publicDriver.schema";
export * from "./vehicleGroup.schema";
